export const DISPLAY_ALERT = "SHOW_ALERT"
export const CLEAR_ALERT = "CLEAR_ALERT"
export const UPLOAD_PIC_BEGIN = "UPLOAD_PIC_BEGIN"
export const UPLOAD_PIC_SUCCESS = "UPLOAD_PIC_SUCCESS"

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN"
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS"
export const SETUP_USER_ERROR = "SETUP_USER_ERROR"

export const LOGOUT_USER = "LOGOUT_USER"

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR"

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR"
export const GROUP_SIDEBAR = "GROUP_SIDEBAR"
export const CLEAR_SIDEBAR = "CLEAR_SIDEBAR"
export const TOGGLE_PROFILE_MODAL = "TOGGLE_PROFILE_MODAL"
export const TOGGLE_GROUP_MODAL = "TOGGLE_GROUP_MODAL"
export const TOGGLE_CHAT = "TOGGLE_CHAT"
export const TOGGLE_ACTION_BUTTON = "TOGGLE_ACTION_BUTTON"
export const HANDLE_CHANGE = "HANDLE_CHANGE"
export const ADD_USER = "ADD_USER"
export const REMOVE_USER = "REMOVE_USER"

export const ADD_MESSAGE = "ADD_MESSAGE"

export const FETCH_CHATS_BEGIN = "FETCH_CHATS_BEGIN"
export const FETCH_CHATS_SUCCESS = "FETCH_CHATS_SUCCESS"

export const CREATE_CHAT_BEGIN = "CREATE_CHAT_BEGIN"
export const CREATE_CHAT_SUCCESS = "CREATE_CHAT_SUCCESS"

export const RENAME_GROUP_BEGIN = "RENAME_GROUP_BEGIN"
export const RENAME_GROUP_SUCCESS = "RENAME_GROUP_SUCCESS"

export const FETCH_USERS_BEGIN = "FETCH_USERS_BEGIN"
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS"
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR"
